name: RunTests

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
      - name: Testing
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
            DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ -e '
          using Pkg; 
          Pkg.develop(PackageSpec(path=pwd())); 
          Pkg.instantiate();
          Pkg.activate(".");
          Pkg.add("Test");
          Pkg.build();
          
          include("tests/runtests.jl");'
